name: Assign Custom Number

on:
  issues:
    types: [opened]

jobs:
  assign_number:
    runs-on: ubuntu-latest
    steps:
    - name: Assign custom number
      uses: actions/github-script@v5
      with:
        script: |
          const issueNumber = context.issue.number;
          const prefix = `RISK-${String(issueNumber).padStart(3, '0')}`;
          const issueTitle = `[${prefix}] ${context.payload.issue.title}`;
          
          github.rest.issues.update({
            ...context.issue,
            title: issueTitle
          });
